global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ddos_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ml-processor'
    static_configs:
      - targets: ['ml-processor:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'bgp-controller'
    static_configs:
      - targets: ['bgp-controller:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
